/*
 * SProfTI API
 *
 * Seletor de Profissinais de TI API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rubensagnelo@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace SProfTIAPI.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Carteirausuarioitem : IEquatable<Carteirausuarioitem>
    { 
        /// <summary>
        /// Identificador da carteira
        /// </summary>
        /// <value>Identificador da carteira</value>
        [Required]
        [DataMember(Name="idCarteira")]
        public int? IdCarteira { get; set; }

        /// <summary>
        /// Identificador da plataforma
        /// </summary>
        /// <value>Identificador da plataforma</value>
        [Required]
        [DataMember(Name="idplataforma")]
        public int? Idplataforma { get; set; }

        /// <summary>
        /// IIdentificado do usuário na plataforma retornado pela API da plataforma
        /// </summary>
        /// <value>IIdentificado do usuário na plataforma retornado pela API da plataforma</value>
        [Required]
        [DataMember(Name="idusuarioplataforma")]
        public string Idusuarioplataforma { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Carteirausuarioitem {\n");
            sb.Append("  IdCarteira: ").Append(IdCarteira).Append("\n");
            sb.Append("  Idplataforma: ").Append(Idplataforma).Append("\n");
            sb.Append("  Idusuarioplataforma: ").Append(Idusuarioplataforma).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Carteirausuarioitem)obj);
        }

        /// <summary>
        /// Returns true if Carteirausuarioitem instances are equal
        /// </summary>
        /// <param name="other">Instance of Carteirausuarioitem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Carteirausuarioitem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IdCarteira == other.IdCarteira ||
                    IdCarteira != null &&
                    IdCarteira.Equals(other.IdCarteira)
                ) && 
                (
                    Idplataforma == other.Idplataforma ||
                    Idplataforma != null &&
                    Idplataforma.Equals(other.Idplataforma)
                ) && 
                (
                    Idusuarioplataforma == other.Idusuarioplataforma ||
                    Idusuarioplataforma != null &&
                    Idusuarioplataforma.Equals(other.Idusuarioplataforma)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IdCarteira != null)
                    hashCode = hashCode * 59 + IdCarteira.GetHashCode();
                    if (Idplataforma != null)
                    hashCode = hashCode * 59 + Idplataforma.GetHashCode();
                    if (Idusuarioplataforma != null)
                    hashCode = hashCode * 59 + Idusuarioplataforma.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Carteirausuarioitem left, Carteirausuarioitem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Carteirausuarioitem left, Carteirausuarioitem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
