/*
 * SProfTI API
 *
 * Seletor de Profissinais de TI API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rubensagnelo@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace SProfTIAPI.Entities
{ 

    public partial class Carteirausuario
    { 
        /// <summary>
        /// Identificador da carteira
        /// </summary>
        /// <value>Identificador da carteira</value>
        public int? IdCarteira { get; set; }

        /// <summary>
        /// Identificador da plataforma
        /// </summary>
        /// <value>Identificador da plataforma</value>
        public int? Idplataforma { get; set; }

        /// <summary>
        /// IIdentificado do usuário na plataforma retornado pela API da plataforma
        /// </summary>
        /// <value>IIdentificado do usuário na plataforma retornado pela API da plataforma</value>
        public string Idusuarioplataforma { get; set; }
 
    }
}
