/*
 * SProfTI API
 *
 * Seletor de Profissinais de TI API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rubensagnelo@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace SProfTIAPI.Entities
{ 
       public partial class Usuarioplataformaitem 
    { 
        /// <summary>
        /// Identificado do usuário na plataforma retornado pela API da plataforma
        /// </summary>
        /// <value>Identificado do usuário na plataforma retornado pela API da plataforma</value>
         public int? Idplataforma { get; set; }

        /// <summary>
        /// Identificador do usuário na plataforma (user_id no StackOverflow e id no GitHub)
        /// </summary>
        /// <value>Identificador do usuário na plataforma (user_id no StackOverflow e id no GitHub)</value>
         public string Idusuarioplatafaorma { get; set; }

        /// <summary>
        /// nome do usuáriodescrito na plataforma
        /// </summary>
        /// <value>nome do usuáriodescrito na plataforma</value>
         public string Nome { get; set; }

        /// <summary>
        /// url da imagem do avatar  (profile_image no StackOverflow e avatar_url no GitHub
        /// </summary>
        /// <value>url da imagem do avatar  (profile_image no StackOverflow e avatar_url no GitHub</value>
         public string Avatar { get; set; }

        /// <summary>
        /// e-mail do usuário da
        /// </summary>
        /// <value>e-mail do usuário da</value>
         public string Email { get; set; }

        /// <summary>
        /// valor resultante de formula que cruza alguns dados do usuários nas respectivas plataformas
        /// </summary>
        /// <value>valor resultante de formula que cruza alguns dados do usuários nas respectivas plataformas</value>
         public int? Reputacao { get; set; }

         public string localizacao { get; set; }

 
    }
}
